ALTER TABLE player COMMENT = '玩家基础信息表';
ALTER TABLE player
    MODIFY id BIGINT NOT NULL COMMENT '玩家ID，雪花算法生成',
    MODIFY open_id VARCHAR(128) NOT NULL COMMENT '微信 openId；开发期使用 dev_code',
    MODIFY nick_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '玩家昵称',
    MODIFY avatar_url VARCHAR(512) NOT NULL DEFAULT '' COMMENT '玩家头像URL',
    MODIFY level INT NOT NULL DEFAULT 1 COMMENT '玩家等级',
    MODIFY exp BIGINT NOT NULL DEFAULT 0 COMMENT '玩家经验值',
    MODIFY coins BIGINT NOT NULL DEFAULT 0 COMMENT '当前金币余额',
    MODIFY total_income BIGINT NOT NULL DEFAULT 0 COMMENT '历史累计收入，用于总榜',
    MODIFY daily_income BIGINT NOT NULL DEFAULT 0 COMMENT '当日收入，用于每日榜',
    MODIFY last_login_at DATETIME NULL COMMENT '最近登录时间',
    MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除';

ALTER TABLE player_land COMMENT = '玩家土地状态表';
ALTER TABLE player_land
    MODIFY id BIGINT NOT NULL COMMENT '土地ID，雪花算法生成',
    MODIFY player_id BIGINT NOT NULL COMMENT '玩家ID',
    MODIFY land_index INT NOT NULL COMMENT '土地序号，从1开始，用于客户端展示排序',
    MODIFY status VARCHAR(32) NOT NULL DEFAULT 'EMPTY' COMMENT '土地状态：EMPTY空地，GROWING种植中',
    MODIFY crop_id VARCHAR(64) NULL COMMENT '当前种植作物ID，对应作物配置 cropId',
    MODIFY planted_at DATETIME NULL COMMENT '播种时间',
    MODIFY mature_at DATETIME NULL COMMENT '成熟时间',
    MODIFY unlocked TINYINT NOT NULL DEFAULT 1 COMMENT '是否已解锁：0未解锁，1已解锁',
    MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除';

ALTER TABLE player_inventory COMMENT = '玩家仓库物品表';
ALTER TABLE player_inventory
    MODIFY id BIGINT NOT NULL COMMENT '仓库记录ID，雪花算法生成',
    MODIFY player_id BIGINT NOT NULL COMMENT '玩家ID',
    MODIFY item_id VARCHAR(64) NOT NULL COMMENT '物品ID，例如 tomato、corn、lettuce',
    MODIFY item_type VARCHAR(32) NOT NULL COMMENT '物品类型：CROP作物，MATERIAL材料，PROP道具',
    MODIFY quantity BIGINT NOT NULL DEFAULT 0 COMMENT '物品数量',
    MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除';

ALTER TABLE player_upgrade COMMENT = '玩家升级状态表';
ALTER TABLE player_upgrade
    MODIFY id BIGINT NOT NULL COMMENT '升级记录ID，雪花算法生成',
    MODIFY player_id BIGINT NOT NULL COMMENT '玩家ID',
    MODIFY upgrade_type VARCHAR(32) NOT NULL COMMENT '升级类型：FARM农场，STALL摊位，WAREHOUSE仓库，DECORATION装饰',
    MODIFY target_id VARCHAR(64) NOT NULL COMMENT '升级目标ID，例如 stall_main、warehouse_main',
    MODIFY level INT NOT NULL DEFAULT 1 COMMENT '当前等级',
    MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除';

ALTER TABLE stall_session COMMENT = '摆摊营业局记录表';
ALTER TABLE stall_session
    MODIFY id BIGINT NOT NULL COMMENT '摆摊局ID，雪花算法生成',
    MODIFY player_id BIGINT NOT NULL COMMENT '玩家ID',
    MODIFY session_no VARCHAR(64) NOT NULL COMMENT '摆摊局业务编号，用于幂等结算',
    MODIFY status VARCHAR(32) NOT NULL DEFAULT 'RUNNING' COMMENT '局状态：RUNNING进行中，FINISHED已结算，CANCELLED已取消',
    MODIFY started_at DATETIME NOT NULL COMMENT '开局时间',
    MODIFY ended_at DATETIME NULL COMMENT '结束时间',
    MODIFY duration_seconds INT NOT NULL DEFAULT 60 COMMENT '营业时长，单位秒',
    MODIFY order_count INT NOT NULL DEFAULT 0 COMMENT '订单总数',
    MODIFY success_order_count INT NOT NULL DEFAULT 0 COMMENT '成功完成订单数',
    MODIFY combo_max INT NOT NULL DEFAULT 0 COMMENT '最大连击数',
    MODIFY thief_handled_count INT NOT NULL DEFAULT 0 COMMENT '成功处理小偷事件次数',
    MODIFY tycoon_completed_count INT NOT NULL DEFAULT 0 COMMENT '完成财富大亨订单次数',
    MODIFY coins_earned BIGINT NOT NULL DEFAULT 0 COMMENT '本局获得金币',
    MODIFY client_payload JSON NULL COMMENT '客户端上报结算明细JSON，用于审计',
    MODIFY server_payload JSON NULL COMMENT '服务端校验结算明细JSON，用于审计',
    MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除';

ALTER TABLE economy_log COMMENT = '金币经济流水表';
ALTER TABLE economy_log
    MODIFY id BIGINT NOT NULL COMMENT '经济流水ID，雪花算法生成',
    MODIFY player_id BIGINT NOT NULL COMMENT '玩家ID',
    MODIFY change_type VARCHAR(64) NOT NULL COMMENT '变动类型：COIN_ADD金币增加，COIN_COST金币消耗',
    MODIFY amount BIGINT NOT NULL COMMENT '变动数量，正数表示增加或消耗的绝对值',
    MODIFY before_amount BIGINT NOT NULL COMMENT '变动前金币余额',
    MODIFY after_amount BIGINT NOT NULL COMMENT '变动后金币余额',
    MODIFY biz_type VARCHAR(64) NOT NULL COMMENT '业务类型：HARVEST、SELL_ITEM、STALL_FINISH、AD_REWARD、UPGRADE',
    MODIFY biz_id VARCHAR(128) NOT NULL COMMENT '业务ID，用于幂等和追溯',
    MODIFY remark VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注说明',
    MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE ad_reward_record COMMENT = '广告奖励领取记录表';
ALTER TABLE ad_reward_record
    MODIFY id BIGINT NOT NULL COMMENT '广告奖励记录ID，雪花算法生成',
    MODIFY player_id BIGINT NOT NULL COMMENT '玩家ID',
    MODIFY reward_type VARCHAR(64) NOT NULL COMMENT '奖励类型：DOUBLE_STALL、INSTANT_MATURE、DAILY_GIFT等',
    MODIFY client_request_id VARCHAR(128) NOT NULL COMMENT '客户端请求ID，用于防重复领取',
    MODIFY reward_payload JSON NULL COMMENT '奖励内容JSON',
    MODIFY claimed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '领取时间';

ALTER TABLE achievement_progress COMMENT = '玩家成就进度表';
ALTER TABLE achievement_progress
    MODIFY id BIGINT NOT NULL COMMENT '成就进度ID，雪花算法生成',
    MODIFY player_id BIGINT NOT NULL COMMENT '玩家ID',
    MODIFY achievement_id VARCHAR(64) NOT NULL COMMENT '成就ID，对应成就配置',
    MODIFY progress BIGINT NOT NULL DEFAULT 0 COMMENT '当前进度值',
    MODIFY completed TINYINT NOT NULL DEFAULT 0 COMMENT '是否完成：0未完成，1已完成',
    MODIFY completed_at DATETIME NULL COMMENT '完成时间',
    MODIFY reward_claimed TINYINT NOT NULL DEFAULT 0 COMMENT '奖励是否已领取：0未领取，1已领取',
    MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记：0未删除，1已删除';

ALTER TABLE game_config_version COMMENT = '游戏配置版本表';
ALTER TABLE game_config_version
    MODIFY id BIGINT NOT NULL COMMENT '配置版本记录ID，雪花算法生成',
    MODIFY config_type VARCHAR(64) NOT NULL COMMENT '配置类型：crop、recipe、upgrade、random_event等',
    MODIFY version VARCHAR(64) NOT NULL COMMENT '配置版本号',
    MODIFY content_hash VARCHAR(128) NOT NULL COMMENT '配置内容哈希，用于客户端判断是否更新',
    MODIFY enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：0禁用，1启用',
    MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
